### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Jonkke** [JoakimJoensuu/ot-harjoitustyo#1]
Harjoitustyö ladattu katselmoitavaksi 26.4 klo 10:30

Pakkausrakenne on selkeä ja kompakti. UI ja ohjelmalogiikka erotettu toisistaan hyvin.

Kurssin koodiin liittyvät laatuvaatimukset toteutuvat erinomaisesti. Luokkien, metodien ja muuttujien nimeäminen noudattaa suosituksia, koodissa ei ole juurikaan toistoa tai liian pitkiä metodeja (UI poislukien, jota nämä säännöt eivät ilmeisesti koskeneet) ja single responsibility -periaate toteutuu luokissa ja metodeissa asianmukaisesti. Luokkien ja metodien JavaDocit selkeitä ja rittävän kattavia.

Testit vaikuttavat myöskin riittävän kattavilta ja testaavat ohjelman toiminnan kannalta olennaisia asioita.

Vaikea keksiä mitään oikeaa valitettavaa. Jos nyt on pakko jostakin sanoa jotain, niin Generator-luokassa cost- ja value-averaging -strategioiden metodeja olisi voinut ehkä jotenkin yhdistellä ylimääräisten parametrien avulla koodin kokonaismäärän vähentämiseksi. Toisaalta ihan hyvä ja kurssin hengen mukaista että kummallekin strategialle on omat metodinsa (single responsibility jne), vaikka esimerkiksi metodit generateCostAverageValues ja generateValueAverageValues ovat nähdäkseni toiminnallisesti identtisiä. Myöskin erillisten utility-metodien roundToInt ja roundToNDecimals tarpeellisuus (siis erillisinä metodeinaan) on vähän kyseenalainen.

Tämä pomppasi silmille: 
Päänäkymässä "Luo manuaalisesti" ja "Generoi" -nappien painaminen asettamatta ylempiä arvoja ei anna UI:ssa mitään virheilmoitusta, vaan oksentaa stacktracken terminaaliin. Sama tapahtuu, jos manuaalisen luonnin sivulla jättää tyhjiä kenttiä.

Kehitysehdotus: generaattorille voisi vaihtelutason lisäksi pystyä antamaan toisena parametrina tiedon siitä, tulisiko kohteen kurssin yleistrendin olla laskeva vai nouseva, sen sijaan että se olisi täysin satunnainen.

Kaikenkaikkiaan erinomaista työtä.

**Comment by JoakimJoensuu** [comment]
Thanks! Tästä oli apua
